import PatientWraper from "@/wraper/PatientWraper";
import "./globals.css";

import { Manrope } from "next/font/google";

const manrope = Manrope({
  weight: ["400", "500", "700", "800"],
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${manrope.className}  antialiased`}>
        <PatientWraper>{children}</PatientWraper>
      </body>
    </html>
  );
}
